print("First Timestamp ")
h1 =input("Enter Hours: ")
m1 =input("Enter Minutes: ")
s1 =input("Enter Seconds: ")
print("Second Timestamp ")
h2 =input("Enter Hours: ")
m2 =input("Enter Minutes: ")
s2 =input("Enter Seconds: ")
firsttimestamp = int(h1) * 3600 + int(m1) * 60 + int(s1)
secondtimestamp = int(h2) * 3600 + int(m2) * 60 + int(s2)
timeinbetween = secondtimestamp - firsttimestamp
print(timeinbetween)