print("First Timestamp ")
h =input("Enter Hours: ")
m =input("Enter Minutes: ")
s =input("Enter Seconds: ")
print("Second Timestamp ")
h =input("Enter Hours: ")
m =input("Enter Minutes: ")
s2 =input("Enter Seconds: ")
timeinbetween = int(s) + int(s2)
print(timeinbetween)